backup/src/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from .. import db
from ..forms import UserCreateForm, UserLoginForm, UserModifyForm

import functools

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    lnId = session.get('user_id')

    if request.method == 'POST' and form.validate_on_submit():
        user = db.select_userInfoByName(form.username.data)
        if not user:
            bizNum = db.select_createBizNum()
            db.insert_userInfo(bizNum, form.username.data, generate_password_hash(form.password1.data), form.rankcd.data, form.deptcd.data, form.phonenum.data, form.hiredt.data, form.remark.data, lnId)
            if form.mnlyn.data == 'N':
              mnl_dnum = 0
              exhaust = 0.0
              leftover = 15.0
            else:
              mnl_dnum = form.mnldnum.data
              exhaust = 0.0
              leftover = form.mnldnum.data+'.0'
            db.insert_userVacInfo(bizNum, form.username.data, form.rankcd.data, form.deptcd.data, exhaust, leftover, form.mnlyn.data, mnl_dnum, lnId)
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    dept_list = db.select_commCdList('DEPT_CD')   
    rank_list = db.select_commCdList('RANK_CD') 
    return render_template('auth/signup.html', form=form, dept_list=dept_list, rank_list=rank_list)

@bp.route('/modify/<string:biznum>', methods=('GET', 'POST'))
def modify(biznum):
    form = UserModifyForm()
    lnId = session.get('user_id')
    user = db.select_userInfoById(biznum)
    if request.method == 'POST' and form.validate_on_submit():
      if g.level == 'super' or g.level == 'admin':
        db.update_userInfo(form.phonenum.data, form.rankcd.data, form.deptcd.data, form.remark.data, form.hiredt.data, form.email.data, biznum, lnId)  
      else:
        db.update_userInfo(form.phonenum.data, user[0][6], user[0][7], form.remark.data, user[0][2], form.email.data, biznum, lnId)
      if form.mnlyn.data == 'N':
        mnl_dnum = 0
        exhaust = 0.0
        leftover = 15.0
      else:
        mnl_dnum = form.mnldnum.data
        exhaust = 0.0
        leftover = form.mnldnum.data+'.0'
      db.update_userVacInfo(exhaust, leftover, form.mnlyn.data, mnl_dnum, lnId, biznum, 'g1')
      return redirect(url_for('main.index'))    
        
    dept_list = db.select_commCdList('DEPT_CD')   
    rank_list = db.select_commCdList('RANK_CD')
    my_vac_list = db.select_myVacList(biznum) 
    return render_template('auth/modify.html', form=form, user=user, dept_list=dept_list, rank_list=rank_list, my_vac_list=my_vac_list)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()  
    
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = db.select_userInfoById(form.biznum.data)  
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user[0][14], form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user[0][0]
            session['level_cd'] = user[0][6]
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = db.select_userInfoById(user_id)

@bp.before_app_request
def user_auth():
    user_id = session.get('user_id')
    level_cd = session.get('level_cd')
    if user_id is None:
        g.auth = None
    else:
        g.auth = level_cd
        if g.auth == 'MD111' or g.auth == 'MD112':
            g.level = 'super'
        elif g.auth == 'MD119':
            g.level = 'admin'
        else:
            g.level = None

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

backup/src/views/info_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, flash, session, g
from werkzeug.utils import redirect
from werkzeug.security import generate_password_hash
from .. import db
from ..forms import UserLoginForm

bp = Blueprint('userinfo', __name__, url_prefix='/userinfo')

@bp.route('/infolist/')
def infolist():
    user_id = session.get('user_id')

    vac_req_list=None
    if g.level == 'super' or g.level == 'admin':
      info_list = db.select_userInfoList('','super')
      vac_req_list = db.select_vacReqList()
    else:
      info_list = db.select_userInfoList(user_id, 'none')
    
    vac_list = db.select_dailyVacList()
    return render_template('userinfo/info.html', info_list=info_list, vac_list=vac_list, vac_req_list=vac_req_list)

@bp.route('/change_pwd/', methods=('GET', 'POST'))
def changepwd():
    form = UserLoginForm()  
    if request.method == 'POST' and form.validate_on_submit():
        db.update_userPwd(generate_password_hash(form.password.data), session.get('user_id')) 
        return redirect(url_for('main.index'))
    return render_template('userinfo/change_pwd.html', form=form)

backup/src/views/vac_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from .. import db
from ..forms import UserVacForm
from datetime import datetime

bp = Blueprint('uservac', __name__, url_prefix='/uservac')

@bp.route('/vacinfo/', methods=('GET', 'POST'))
def vacinfo():
  form = UserVacForm()
  if request.method == 'POST' and form.validate_on_submit():
    now = datetime.now()
    str_now = now.strftime("%Y%m%d")
    if form.actiontype.data == 'SAVE':
      cnt = db.select_userVacInfoExists(form.biznum.data, form.vacdt.data)
      if cnt[0][0] > 0:
        flash(form.vacdt.data+'일 휴가가 존재합니다.')
      else:      
        db.update_userVacInfo(form.exhaust.data, form.leftover.data, form.mnlyn.data, form.mnldnum.data, session.get('user_id'), form.biznum.data, 'g1')
        db.insert_userVacHistInfo(session.get('user_id'), form.vacdt.data, str_now, form.vacty.data, form.vacapty.data, form.prosts.data, form.vacsts.data, form.remark.data, session.get('user_id'))
    elif form.actiontype.data == 'MODIFY':
      db.update_userVacInfo(form.exhaust.data, form.leftover.data, form.mnlyn.data, form.mnldnum.data, session.get('user_id'), form.biznum.data, 'g1')
      db.delete_userVacHistInfo(form.biznum.data, form.prevacdt.data)
      db.insert_userVacHistInfo(session.get('user_id'), form.vacdt.data, str_now, form.vacty.data, form.vacapty.data, form.prosts.data, form.vacsts.data, form.remark.data, session.get('user_id'))
    elif form.actiontype.data == 'CANCEL':
      db.update_userVacInfo(form.exhaust.data, form.leftover.data, form.mnlyn.data, form.mnldnum.data, session.get('user_id'), form.biznum.data, 'g1')
      db.delete_userVacHistInfo(form.biznum.data, form.vacdt.data)
    elif form.actiontype.data == 'AGREE':
      db.update_userVacHistInfo(form.prosts.data, session.get('user_id'), form.biznum.data, form.vacdt.data)
    elif form.actiontype.data == 'DENY':
      #db.update_userVacInfo(form.exhaust.data, form.leftover.data, '', '', session.get('user_id'), form.biznum.data, 'g2')
      db.update_userVacHistInfo(form.prosts.data, session.get('user_id'), form.biznum.data, form.vacdt.data)


  user = db.select_userInfoById(session.get('user_id'))
  my_vac_list = db.select_myVacList(session.get('user_id'))
  vac_req_list = db.select_vacReqList()

  vac_ty = db.select_commCdList('M0004')
  vac_ap_ty = db.select_commCdList('M0005')
  vac_sts = db.select_commCdList('M0009')
  return render_template('uservac/vacinfo.html', form=form, my_vac_list=my_vac_list, user=user, vac_ty=vac_ty, vac_ap_ty=vac_ap_ty, vac_sts=vac_sts, vac_req_list=vac_req_list)

backup/src/templates/userinfo/change_pwd.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
      <input type="hidden" name="biznum" id="biznum" value="{{g.user[0][0]}}"/>  
        {{ form.csrf_token }}
        {% include "form_errors.html" %}
        <div class="form-group">
          <label for="password1">비밀번호</label>
          <input type="password" class="form-control" name="password" id="password"
                 value="{{ form.password.data or '' }}">
      </div>
        <button type="submit" class="btn btn-primary">저장</button>
    </form>
</div>
{% endblock %}

backup/src/templates/userinfo/info.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3" style="max-width: 1500px; width: auto;">
  <div class="row my-3">
      <div class="card-body">
        <div class="card-text" style="white-space: pre-line;">기본정보</div>
      </div> 
      <table class="table">
          <thead>
          <tr class="text-center thead-dark">
              <th>사번</th>
              <th>이름</th>
              <th>직책</th>
              <th>부서</th>
              <th>입사일</th>
              <th>수동할당여부</th>
              <th>할당일</th>
              <th>휴가소진일수</th>
              <th>잔여일수</th>
          </tr>
          </thead>
          <tbody>
          {% if info_list %}
          {% for info in info_list %}
            <tr class="text-center">
              <td><a class="nav-link" href="{{ url_for('auth.modify', biznum=info[0]) }}">{{ info[0] }}</a></td>
              <td>{{ info[1] }}</td>
              <td>{{ info[7] }}</td>
              <td>{{ info[8] }}</td>
              <td>{{ info[2] }}</td>
              <td>{{ info[3] }}</td>
              <td>{{ info[4] }}</td>
              <td>{{ info[5] }}</td>
              <td>{{ info[6] }}</td>
<!--              <td>{{ info[7] }}</td>-->
            </tr>
          {% endfor %}
          {% endif %}
          </tbody>
      </table>
  </div>
  <div class="row my-3"> 
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line;">휴가현황 (금일기준 +14일까지 승인건에 한함)</div>
    </div> 
    <table class="table">
      <thead>
      <tr class="text-center thead-dark">
          <th>사번</th>
          <th>이름</th>
          <th>휴가일</th>
          <th>휴가종류</th>
          <th>휴가신청유형</th>
          <th>진행상태</th>
          <th>휴가상태</th>
      </tr>
      </thead>
      <tbody>
      {% if vac_list %}
      {% for vac in vac_list %}
        {% if vac[8] == 'Y' %}
        <tr class="text-center" style="font-weight:bold !important">
        {% else %}
        <tr class="text-center">
        {% endif %}
          <td>{{ vac[0] }}</td>
          <td>{{ vac[1] }}</td>
          <td>{{ vac[2] }}</td>
          <td>{{ vac[3] }}</td>
          <td>{{ vac[4] }}</td>
          <td>{{ vac[5] }}</td>
          <td>{{ vac[6] }}</td>
      </tr>
      {% endfor %}
      {% endif %}
      </tbody>
    </table>
  </div>
  {% if g.level %}
  <div class="row my-3"> 
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line;">휴가신청 현황</div>
    </div> 
    <table class="table">
      <thead>
      <tr class="text-center thead-dark">
          <th>사번</th>
          <th>이름</th>
          <th>휴가일</th>
          <th>휴가종류</th>
          <th>휴가신청유형</th>
          <th>진행상태</th>
          <th>휴가상태</th>
      </tr>
      </thead>
      <tbody>
      {% if vac_req_list %}
      {% for vac in vac_req_list %}
      <tr class="text-center">
          <td>{{ vac[0] }}</td>
          <td>{{ vac[1] }}</td>
          <td>{{ vac[2] }}</td>
          <td>{{ vac[3] }}</td>
          <td>{{ vac[4] }}</td>
          <td>{{ vac[5] }}</td>
          <td>{{ vac[6] }}</td>          
      </tr>
      {% endfor %}
      {% endif %}
      </tbody>
    </table>
  </div>
  {% endif %}
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
  function saveVacProgress(param, biznum, vacdt, vacty, vacsts, _exhaust, _leftover, msg) {    
    if (confirm("휴가신청을 "+msg+"하시겠습니까? ")) {
      $('#biznum').val(biznum);
      $('#vacdt').val(vacdt);
      if(param == 'agree') {
        $("#actiontype").val('AGREE');    
        $('#prosts').val('MD602')
      } else {
        var leftover = _leftover;
        var exhaust = _exhaust;
        if(vacsts == 'MD901') {
          if(vacty == 'MD402' || vacty == 'MD403') {  // 휴가종류가 반차인경우
            leftover = parseFloat(leftover) + 0.5;
            exhaust = parseFloat(exhaust) - 0.5;
          } else {  // 휴가종류가 전일인 경우
            leftover = parseFloat(leftover) + 1;
            exhaust = parseFloat(exhaust) - 1;
          }
        }
        $('#exhaust').val(exhaust);
        $('#leftover').val(leftover);
        $("#actiontype").val('DENY');
        $('#prosts').val('MD603');
      }
      $("#detailForm").attr("action","{{ url_for('uservac.vacinfo') }}");
      $("#detailForm").submit();
    } else {
      
    }    
  }
</script>
{% endblock %}