backup/src/views/mgmt_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, jsonify

from .. import db
from ..forms import mgmtSrchForm, mgmtDetailForm
from datetime import datetime

bp = Blueprint('mgmt', __name__, url_prefix='/mgmt')

@bp.route('/mgmtinfo/', methods=('GET', 'POST'))
def mgmtinfo():
  form = mgmtSrchForm()
  if request.method == 'GET':
    mstcd = request.args.get('mstcd', type=str, default='ALL')
    detcd = request.args.get('detcd', type=str, default='ALL')
    stdt = request.args.get('stdt', type=str, default='')
    eddt = request.args.get('eddt', type=str, default='')
    useyn = request.args.get('useyn', type=str, default='Y')

  gubun = 'ALL'
  if(mstcd != 'ALL'):
    gubun = 'MST'

  if(mstcd != 'ALL' and detcd != '1'):
    gubun = 'DET'

  mgmt_list = db.select_mgmtList(stdt, eddt, useyn, mstcd, detcd, gubun)

  mst_cd = db.select_commCdMgmtList()
  return render_template('mgmt/mgmtinfo.html', form=form, mgmt_list=mgmt_list, mst_cd=mst_cd, mstcd=mstcd, detcd=detcd)

@bp.route('/mgmtinfo/get_items', methods=['POST']) 
def add_items(): 
  mst_cd = request.form['mst_cd']  
  det_cd = db.select_commCdList(mst_cd)
  return jsonify(det_cd)

@bp.route('/register/', methods=('GET', 'POST'))
def register():
    form = mgmtDetailForm()

    if request.method == 'POST' and form.validate_on_submit():
      now = datetime.now()
      str_now = now.strftime("%Y%m%d")
      seriallist = request.values.getlist('serialnum')
      datatx1list = request.values.getlist('datatx1')
      datatx2list = request.values.getlist('datatx2')
      for i in range(len(seriallist)):
        if(seriallist[i] != ''):
          db.insert_mgmtdata(str_now, form.mstcd.data, form.detcd.data, datatx1list[i], datatx2list[i], seriallist[i])

    mst_cd = db.select_commCdMgmtList()
    return render_template('mgmt/register.html', form=form, mst_cd=mst_cd)

@bp.route('/mgmtdetail/<string:mgmtnum>', methods=('GET', 'POST'))
def mgmtdetail(mgmtnum):
    form = mgmtDetailForm()

    if request.method == 'POST' and form.validate_on_submit():
      db.update_mgmtInfo(form.datatx1.data, form.datatx2.data, form.datatx3.data, form.datanum1.data, form.datanum2.data, form.datanum3.data, form.useyn.data, session.get('user_id'), form.mgmtnum.data)

      
    detail = db.select_mgmtInfo(mgmtnum)
    return render_template('mgmt/detail.html', form=form, detail=detail, mgmtnum=mgmtnum)

backup/src/templates/mgmt/detail.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
  <a href="#" class="btn btn-primary" id="btn_save">저장</a>
  <form method="post" class="post-form" id="detailForm">
    <div class="row my-3">
      <div class="card-body">
        <div class="card-text" style="white-space: pre-line;">상세정보</div>
      </div>
      <table class="table" id="detailTable">
        {{ form.csrf_token }}
        {% include "form_errors.html" %}
          <tr class="text-center thead-dark">
            <th>관리번호</th>
            <td colspan="3">
              <input type="text" class="form-control" name="mgmtnum" id="mgmtnum" value="{{detail[0][0]}}" readonly>
            </td>
          </tr>
          <tr class="text-center thead-dark">
            <th>등록일자</th>
            <td><input type="text" class="form-control" name="strddt" id="strddt" value="{{detail[0][1]}}" readonly></td>
            <th>일련번호</th>
            <td><input type="text" class="form-control" name="serialnum" id="serialnum" value="{{detail[0][12]}}" readonly></td>
          </tr>   
          <tr class="text-center thead-dark">
            <th>마스터코드</th>
            <td><input type="text" class="form-control" name="mstcd" id="mstcd" value="{{detail[0][2]}}" readonly></td>
            <th>마스터코드명</th>
            <td><input type="text" class="form-control" name="mstnm" id="mstnm" value="{{detail[0][3]}}" readonly></td>
          </tr>   
          <tr class="text-center thead-dark">
            <th>상세코드</th>
            <td><input type="text" class="form-control" name="detcd" id="detcd" value="{{detail[0][4]}}" readonly></td>
            <th>상세코드명</th>
            <td><input type="text" class="form-control" name="detnm" id="detnm" value="{{detail[0][5]}}" readonly></td>
          </tr>   
          <tr class="text-center thead-dark">
            <th>데이터1</th>
            <td colspan="3"><input type="text" class="form-control" name="datatx1" id="datatx1" value="{{detail[0][6]}}" rows=3></td>
          </tr>    
          <tr class="text-center thead-dark">
            <th>데이터2</th>
            <td colspan="3"><input type="text" class="form-control" name="datatx2" id="datatx2" value="{{detail[0][7]}}" rows=3></td>
          </tr>
          <tr class="text-center thead-dark">
            <th>데이터3</th>
            <td colspan="3"><input type="text" class="form-control" name="datatx3" id="datatx3" value="{{detail[0][8]}}" rows=3></td>
          </tr>   
          <tr class="text-center thead-dark">
            <th>데이터 숫자1</th>
            <td><input type="text" class="form-control" name="datanum1" id="datanum1" value="{{detail[0][9]}}"></td>
            <th>USE Y/N</th>
            <td>
              <select class="form-control so" name="useyn" id="useyn">
                <option value="Y">Y</option>
                <option value="N">N</option>
              </select>
            </td>
          </tr>   
          <tr class="text-center thead-dark">
            <th>데이터 숫자2</th>
            <td colspan="3"><input type="text" class="form-control" name="datanum2" id="datanum2" value="{{detail[0][10]}}" rows=3></td>
          </tr> 
          <tr class="text-center thead-dark">
            <th>데이터 숫자3</th>
            <td colspan="3"><input type="text" class="form-control" name="datanum3" id="datanum3" value="{{detail[0][11]}}" rows=3></td>
          </tr>                  
        </table>
    </div>
  </form>  
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){

  $('#useyn').val('{{detail[0][13]}}')

  $('#btn_save').on('click', function() {
    if (confirm("저장하시겠습니까? ")) {
      $('#detailForm').submit();
    }    
  });

});
</script>
{% endblock %} 

backup/src/templates/mgmt/mgmtinfo.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3" style="max-width: 1500px; width: auto;">
  <form id="searchForm" method="get" action="{{ url_for('mgmt.mgmtinfo') }}">
    <div class="row my-3">
      <div class="col-2 input-group">
        <select class="form-control so" name="mstcd" id="mstcd" style="padding: 0px;">
          {% for mst_cd in mst_cd %}
          <option value="{{ mst_cd[0] }}">{{ mst_cd[1] }} </option>
          {% endfor %}
        </select>
      </div>
      <div class="col-2 input-group">      
        <select class="form-control so" name="detcd" id="detcd" style="padding: 0px;">
          <option value="ALL">ALL</option>
        </select>
      </div>
      <div class="col-3 input-group">
        <input type="text" class="form-control" name="stdt" id="stdt" value="">&nbsp; ~ &nbsp;
        <input type="text" class="form-control" name="eddt" id="eddt" value="">
      </div>
      <div class="col-1 input-group">         
        <select class="form-control so" name="useyn" id="useyn">
          <option value="Y">Y</option>
          <option value="N">N</option>
        </select>        
      </div>
      <div class="col-3 input-group"> 
          <button class="btn btn-outline-secondary" type="button" id="btn_search">검색</button>&nbsp;
          <a href="{{ url_for('mgmt.register') }}" class="btn btn-primary">신규</a>
        </div>
    </div>
  </form>
  <div class="row my-3">
      <div class="card-body">
        <div class="card-text" style="white-space: pre-line;">목록</div>
      </div> 
      <table class="myTable table">
          <thead>
          <tr class="text-center thead-dark">
              <th>관리번호</th>
              <th>DATE</th>
              <th>마스터코드</th>
              <th>마스터코드명</th>
              <th>상세코드</th>
              <th>상세코드명</th>
              <th>데이터1</th>
              <th>데이터2</th>
              <th>자산관리번호</th>
              <th>데이터숫자1</th>
              <th>데이터숫자2</th>
              <th>데이터숫자3</th>
              <th>일련번호</th>
          </tr>
          </thead>
          <tbody>
          {% if mgmt_list %}
          {% for mgmt in mgmt_list %}
            <tr class="text-center">
              <td><a class="nav-link" href="{{ url_for('mgmt.mgmtdetail', mgmtnum=mgmt[0]) }}">{{ mgmt[0] }}</a></td>
              <td>{{ mgmt[1] }}</td>
              <td>{{ mgmt[2] }}</td>
              <td>{{ mgmt[3] }}</td>
              <td>{{ mgmt[4] }}</td>
              <td>{{ mgmt[5] }}</td>
              <td>{{ mgmt[6] }}</td>
              <td>{{ mgmt[7] }}</td>
              <td>{{ mgmt[8] }}</td>
              <td>{{ mgmt[9] }}</td>
              <td>{{ mgmt[10] }}</td>
              <td>{{ mgmt[11] }}</td>
              <td>{{ mgmt[12] }}</td>
            </tr>
          {% endfor %}
          {% endif %}
          </tbody>
      </table>
  </div>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
  let options = {
        numberPerPage:15, //Cantidad de datos por pagina
        goBar:true, //Barra donde puedes digitar el numero de la pagina al que quiere ir
        pageCounter:true, //Contador de paginas, en cual estas, de cuantas paginas
    };
    paginate.init('.myTable',options);

  $(document).ready(function(){
    $('#stdt').datepicker({
      format : "yyyy-mm-dd",
    }).datepicker("setDate", "-12M");

    $('#eddt').datepicker({
      format : "yyyy-mm-dd",
    }).datepicker("setDate", "today");

    
    $('#mstcd').change(function(){
      if($(this).val() == 'ALL') {
        $('#detcd').html('<option value="ALL">ALL</option>');
      } else {
        $.ajax({ 
        type:'POST', 
        url:'/mgmt/mgmtinfo/get_items', 
        data:{ mst_cd: $(this).val() },
        success: function(res){ 
          var html = '';
          $.each(res, function(i, data){
            html += '<option value="'+res[i][0]+'">'+res[i][1]+'</option>';
          });
          $('#detcd').html(html);
        }, error : function(xtr, status, error){ 
          alert(xtr +":"+status+":"+error); 
        } 
      });
      }
    });  
    
    if('{{mstcd}}' != 'ALL') {
      $('#mstcd').val('{{mstcd}}');
      $('#mstcd').trigger('change');
      if('{{detcd}}' != '1') {
        setTimeout(function() {
          $('#detcd').val('{{detcd}}');
        }, 500);
      };
    }
  });

  $('#btn_search').on('click', function() {
    $("#searchForm").submit();
  });

</script>
{% endblock %}

backup/src/templates/mgmt/register.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
  <a href="#" class="btn btn-primary" id="btn_save">저장</a>
  <form method="post" class="post-form" id="detailForm">
    <div class="row my-3">
      <div class="card-body">
        <div class="card-text" style="white-space: pre-line;">상세정보</div>
      </div>
      <table class="table" id="detailTable">
        {{ form.csrf_token }}
        {% include "form_errors.html" %}
          <tr class="text-center thead-dark">
            <th>대분류</th>
            <td colspan="3">
              <select class="form-control" name="mstcd" id="mstcd">
                {% for mst_cd in mst_cd %}
                <option value="{{ mst_cd[0] }}">{{ mst_cd[1] }} </option>
                {% endfor %}
              </select>
            </td>
            <th>중분류</th>
            <td colspan="3">
              <select class="form-control" name="detcd" id="detcd">
                <option value="ALL">ALL</option>
              </select>
            </td>
          </tr>
          <tr class="text-center thead-dark">
            <th>일련번호</th>
            <td><input type="text" class="form-control" name="serialnum" id="serialnum" value=""></td>
            <th>데이터1<input type="button" id="btn_data1" value="일괄적용"/></th>
            <td><input type="text" class="form-control" name="datatx1" id="datatx1" value=""></td>
            <th>데이터2<input type="button" id="btn_data2" value="일괄적용"/></th>
            <td><input type="text" class="form-control" name="datatx2" id="datatx2" value=""></td>
          </tr>                           
        </table>
    </div>
  </form>
  <div id="appendTr" style="display: none;">
    <tr class="text-center thead-dark">
      <th>일련번호</th>
      <td><input type="text" class="form-control" name="serialnum" id="serialnum" value=""></td>
      <th>데이터1</th>
      <td><input type="text" class="form-control" name="datatx1" id="datatx1" value=""></td>
      <th>데이터2</th>
      <td><input type="text" class="form-control" name="datatx2" id="datatx2" value=""></td>
    </tr>
  </div>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
  $('#hiredt').datepicker({
    format : "yyyy-mm-dd",
  });
  
  var html = '<tr class="text-center thead-dark"><th>일련번호</th><td><input type="text" class="form-control" name="serialnum" id="serialnum" value=""></td>';
  html += '<th>데이터1</th><td><input type="text" class="form-control" name="datatx1" id="datatx1" value=""></td>';
  html += '<th>데이터2</th><td><input type="text" class="form-control" name="datatx2" id="datatx2" value=""></td></tr>';
  for (i=0; i<9; i++) {
    $('#detailTable').append(html)
  }
  
  $('#mstcd').change(function(){
    if($(this).val() == 'ALL') {
      $('#detcd').html('<option value="ALL">ALL</option>');
    } else {
      $.ajax({ 
      type:'POST', 
      url:'/mgmt/mgmtinfo/get_items', 
      data:{ mst_cd: $(this).val() },
      success: function(res){ 
        console.log(res) 
        var html = '';
        $.each(res, function(i, data){
          html += '<option value="'+res[i][0]+'">'+res[i][1]+'</option>';
        });
        $('#detcd').html(html);
      }, error : function(xtr, status, error){ 
        alert(xtr +":"+status+":"+error); 
      } 
    });
    }
  });

  $('#btn_save').on('click', function() {
    if($('#mstcd').val() == 'ALL' || $('#detcd').val() == 'ALL') {
      alert('분류를 선택하여 주십시오.');
      return false;
    }
    if (confirm("저장하시겠습니까? ")) {
      $('#detailForm').submit();
    }    
  });

  $('#btn_data1').on('click', function() {
    $('input[name=datatx1]').attr('value',$('#datatx1').val());
  });

  $('#btn_data2').on('click', function() {
    $('input[name=datatx2]').attr('value',$('#datatx2').val());
  });

});
</script>
{% endblock %} 