backup/src/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from .. import db
from ..forms import UserCreateForm, UserLoginForm, UserModifyForm

import functools

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    lnId = session.get('user_id')

    if request.method == 'POST' and form.validate_on_submit():
        user = db.select_userInfoByName(form.username.data)
        if not user:
            bizNum = db.select_createBizNum()
            db.insert_userInfo(bizNum, form.username.data, generate_password_hash(form.password1.data), form.rankcd.data, form.deptcd.data, form.phonenum.data, form.hiredt.data, form.remark.data, lnId)
            if form.mnlyn.data == 'N':
              mnl_dnum = 0
              exhaust = 0.0
              leftover = 15.0
            else:
              mnl_dnum = form.mnldnum.data
              exhaust = 0.0
              leftover = form.mnldnum.data+'.0'
            db.insert_userVacInfo(bizNum, form.username.data, form.rankcd.data, form.deptcd.data, exhaust, leftover, form.mnlyn.data, mnl_dnum, lnId)
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    dept_list = db.select_commCdList('DEPT_CD')   
    rank_list = db.select_commCdList('RANK_CD') 
    return render_template('auth/signup.html', form=form, dept_list=dept_list, rank_list=rank_list)

@bp.route('/modify/<string:biznum>', methods=('GET', 'POST'))
def modify(biznum):
    form = UserModifyForm()
    lnId = session.get('user_id')
    user = db.select_userInfoById(biznum)
    if request.method == 'POST' and form.validate_on_submit():
      if g.level == 'super' or g.level == 'admin':
        db.update_userInfo(form.phonenum.data, form.rankcd.data, form.deptcd.data, form.remark.data, form.hiredt.data, form.email.data, biznum, lnId)  
      else:
        db.update_userInfo(form.phonenum.data, user[0][6], user[0][7], form.remark.data, user[0][2], form.email.data, biznum, lnId)
      if form.mnlyn.data == 'N':
        mnl_dnum = 0
        exhaust = 0.0
        leftover = 15.0
      else:
        mnl_dnum = form.mnldnum.data
        exhaust = 0.0
        leftover = form.mnldnum.data+'.0'
      db.update_userVacInfo(exhaust, leftover, form.mnlyn.data, mnl_dnum, lnId, biznum, 'g1')
      return redirect(url_for('main.index'))    
        
    dept_list = db.select_commCdList('DEPT_CD')   
    rank_list = db.select_commCdList('RANK_CD')
    my_vac_list = db.select_myVacList(biznum) 
    return render_template('auth/modify.html', form=form, user=user, dept_list=dept_list, rank_list=rank_list, my_vac_list=my_vac_list)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()  
    
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = db.select_userInfoById(form.biznum.data)  
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user[0][14], form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user[0][0]
            session['level_cd'] = user[0][6]
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = db.select_userInfoById(user_id)

@bp.before_app_request
def user_auth():
    user_id = session.get('user_id')
    level_cd = session.get('level_cd')
    if user_id is None:
        g.auth = None
    else:
        g.auth = level_cd
        if g.auth == 'MD111' or g.auth == 'MD112':
            g.level = 'super'
        elif g.auth == 'MD119':
            g.level = 'admin'
        else:
            g.level = None

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

backup/src/views/info_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, flash, session, g
from werkzeug.utils import redirect
from werkzeug.security import generate_password_hash
from .. import db
from ..forms import UserLoginForm

bp = Blueprint('userinfo', __name__, url_prefix='/userinfo')

@bp.route('/infolist/')
def infolist():
    user_id = session.get('user_id')

    vac_req_list=None
    if g.level == 'super' or g.level == 'admin':
      info_list = db.select_userInfoList('','super')
      vac_req_list = db.select_vacReqList()
    else:
      info_list = db.select_userInfoList(user_id, 'none')
    
    vac_list = db.select_dailyVacList()
    return render_template('userinfo/info.html', info_list=info_list, vac_list=vac_list, vac_req_list=vac_req_list)

@bp.route('/change_pwd/', methods=('GET', 'POST'))
def changepwd():
    form = UserLoginForm()  
    if request.method == 'POST' and form.validate_on_submit():
        db.update_userPwd(generate_password_hash(form.password.data), session.get('user_id')) 
        return redirect(url_for('main.index'))
    return render_template('userinfo/change_pwd.html', form=form)

backup/src/views/mgmt_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, jsonify

from .. import db
from ..forms import mgmtSrchForm, mgmtDetailForm
from datetime import datetime

bp = Blueprint('mgmt', __name__, url_prefix='/mgmt')

@bp.route('/mgmtinfo/', methods=('GET', 'POST'))
def mgmtinfo():
  form = mgmtSrchForm()
  if request.method == 'GET':
    mstcd = request.args.get('mstcd', type=str, default='ALL')
    detcd = request.args.get('detcd', type=str, default='ALL')
    stdt = request.args.get('stdt', type=str, default='')
    eddt = request.args.get('eddt', type=str, default='')
    useyn = request.args.get('useyn', type=str, default='Y')

  gubun = 'ALL'
  if(mstcd != 'ALL'):
    gubun = 'MST'

  if(mstcd != 'ALL' and detcd != '1'):
    gubun = 'DET'

  mgmt_list = db.select_mgmtList(stdt, eddt, useyn, mstcd, detcd, gubun)

  mst_cd = db.select_commCdMgmtList()
  return render_template('mgmt/mgmtinfo.html', form=form, mgmt_list=mgmt_list, mst_cd=mst_cd, mstcd=mstcd, detcd=detcd)

@bp.route('/mgmtinfo/get_items', methods=['POST']) 
def add_items(): 
  mst_cd = request.form['mst_cd']  
  det_cd = db.select_commCdList(mst_cd)
  return jsonify(det_cd)

@bp.route('/register/', methods=('GET', 'POST'))
def register():
    form = mgmtDetailForm()

    if request.method == 'POST' and form.validate_on_submit():
      now = datetime.now()
      str_now = now.strftime("%Y%m%d")
      seriallist = request.values.getlist('serialnum')
      datatx1list = request.values.getlist('datatx1')
      datatx2list = request.values.getlist('datatx2')
      for i in range(len(seriallist)):
        if(seriallist[i] != ''):
          db.insert_mgmtdata(str_now, form.mstcd.data, form.detcd.data, datatx1list[i], datatx2list[i], seriallist[i])

    mst_cd = db.select_commCdMgmtList()
    return render_template('mgmt/register.html', form=form, mst_cd=mst_cd)

@bp.route('/mgmtdetail/<string:mgmtnum>', methods=('GET', 'POST'))
def mgmtdetail(mgmtnum):
    form = mgmtDetailForm()

    if request.method == 'POST' and form.validate_on_submit():
      db.update_mgmtInfo(form.datatx1.data, form.datatx2.data, form.datatx3.data, form.datanum1.data, form.datanum2.data, form.datanum3.data, form.useyn.data, session.get('user_id'), form.mgmtnum.data)

      
    detail = db.select_mgmtInfo(mgmtnum)
    return render_template('mgmt/detail.html', form=form, detail=detail, mgmtnum=mgmtnum)

backup/src/views/vac_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from .. import db
from ..forms import UserVacForm
from datetime import datetime

bp = Blueprint('uservac', __name__, url_prefix='/uservac')

@bp.route('/vacinfo/', methods=('GET', 'POST'))
def vacinfo():
  form = UserVacForm()
  if request.method == 'POST' and form.validate_on_submit():
    now = datetime.now()
    str_now = now.strftime("%Y%m%d")
    if form.actiontype.data == 'SAVE':
      cnt = db.select_userVacInfoExists(form.biznum.data, form.vacdt.data)
      if cnt[0][0] > 0:
        flash(form.vacdt.data+'일 휴가가 존재합니다.')
      else:      
        db.update_userVacInfo(form.exhaust.data, form.leftover.data, form.mnlyn.data, form.mnldnum.data, session.get('user_id'), form.biznum.data, 'g1')
        db.insert_userVacHistInfo(session.get('user_id'), form.vacdt.data, str_now, form.vacty.data, form.vacapty.data, form.prosts.data, form.vacsts.data, form.remark.data, session.get('user_id'))
    elif form.actiontype.data == 'MODIFY':
      db.update_userVacInfo(form.exhaust.data, form.leftover.data, form.mnlyn.data, form.mnldnum.data, session.get('user_id'), form.biznum.data, 'g1')
      db.delete_userVacHistInfo(form.biznum.data, form.prevacdt.data)
      db.insert_userVacHistInfo(session.get('user_id'), form.vacdt.data, str_now, form.vacty.data, form.vacapty.data, form.prosts.data, form.vacsts.data, form.remark.data, session.get('user_id'))
    elif form.actiontype.data == 'CANCEL':
      db.update_userVacInfo(form.exhaust.data, form.leftover.data, form.mnlyn.data, form.mnldnum.data, session.get('user_id'), form.biznum.data, 'g1')
      db.delete_userVacHistInfo(form.biznum.data, form.vacdt.data)
    elif form.actiontype.data == 'AGREE':
      db.update_userVacHistInfo(form.prosts.data, session.get('user_id'), form.biznum.data, form.vacdt.data)
    elif form.actiontype.data == 'DENY':
      #db.update_userVacInfo(form.exhaust.data, form.leftover.data, '', '', session.get('user_id'), form.biznum.data, 'g2')
      db.update_userVacHistInfo(form.prosts.data, session.get('user_id'), form.biznum.data, form.vacdt.data)


  user = db.select_userInfoById(session.get('user_id'))
  my_vac_list = db.select_myVacList(session.get('user_id'))
  vac_req_list = db.select_vacReqList()

  vac_ty = db.select_commCdList('M0004')
  vac_ap_ty = db.select_commCdList('M0005')
  vac_sts = db.select_commCdList('M0009')
  return render_template('uservac/vacinfo.html', form=form, my_vac_list=my_vac_list, user=user, vac_ty=vac_ty, vac_ap_ty=vac_ap_ty, vac_sts=vac_sts, vac_req_list=vac_req_list)

backup/src/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <!-- nms CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='paginate.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='ligne.css') }}">
    <title>Nexcore Management System</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{{ url_for('static', filename='jquery-3.6.0.min.js') }}"></script>
<!-- Bootstrap JS -->
<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='paginate.js') }}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

backup/src/templates/form_errors.html
<!-- 필드오류 -->
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
</div>
{% endfor %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

backup/src/templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{{ url_for('main.index') }}"><em><b>NMS</b></em></a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">        
        {% if g.user %}
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('userinfo.infolist') }}">사용자기본정보</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('uservac.vacinfo') }}">휴가관리</a>
            </li>
            {% if g.level %}
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('auth.signup') }}">사용자등록</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('mgmt.mgmtinfo') }}">재고관리</a>
            </li>
            {% endif %}
            <li class="nav-item ">
                <a class="nav-link " href="{{ url_for('auth.logout') }}"><b><u>{{g.user[0][1]}} (로그아웃)</u></b></a>
            </li>
            <li class="nav-item ">
              <a class="nav-link " href="{{ url_for('userinfo.changepwd') }}"><b><u>비밀번호 변경</u></b></a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('test.camTest') }}">CAM Test</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('test.camTest2') }}">CAM Test2</a>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('auth.login') }}"><b>로그인</b></a>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>